-- AlterTable
ALTER TABLE `User` ADD COLUMN `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `firstName` VARCHAR(191) NULL,
    ADD COLUMN `lastName` VARCHAR(191) NULL,
    ADD COLUMN `role` INTEGER NULL DEFAULT 0,
    ADD COLUMN `updatedAt` DATETIME(3) NULL;
